version: '3.11'

services:
  flask:
    build: .
    volumes:
      - .:/app
    command: flask run
    ports:
      - "5001:5001"
    environment:
      FLASK_APP: "app.main.py"
      FLASK_ENV: "development"
      FLASK_DEBUG: 1
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: "5001"